// Personal data class of every column of every tenant table
// (docs/data-model.md §3.7). A test fails when a column is missing here.
//
// P  directly identifying (name, e-mail, phone, address)
// I  free content that may contain personal data (summary, mail text)
// V  derived from content (embedding)
// -  no personal data (ids, status, timestamps, amounts)

export type PiiClass = 'P' | 'I' | 'V' | '-';

const source = {
  source_type: '-',
  source_event_id: '-',
  source_user_id: '-',
  source_action_id: '-',
  ai_model: '-',
  ai_trace_id: '-',
} as const;

export const piiRegister: Record<string, Record<string, PiiClass>> = {
  tenant_settings: {
    tenant_id: '-',
    default_vat_rate_bps: '-',
    content_retention_days: '-',
    created_at: '-',
    updated_at: '-',
  },
  entities: {
    id: '-',
    tenant_id: '-',
    type: '-',
    name: 'P',
    attributes: 'P',
    archived_at: '-',
    merged_into_id: '-',
    created_at: '-',
    updated_at: '-',
  },
  entity_identifiers: {
    id: '-',
    tenant_id: '-',
    entity_id: '-',
    kind: '-',
    value: 'P',
    ...source,
    created_at: '-',
  },
  relations: {
    id: '-',
    tenant_id: '-',
    from_entity_id: '-',
    to_entity_id: '-',
    type: '-',
    status: '-',
    valid_from: '-',
    valid_to: '-',
    confirmed_by_user_id: '-',
    confirmed_at: '-',
    ...source,
    created_at: '-',
    updated_at: '-',
  },
  events: {
    id: '-',
    tenant_id: '-',
    source: '-',
    external_id: '-',
    type: '-',
    occurred_at: '-',
    thread_key: '-',
    summary: 'I',
    summarized_at: '-',
    payload: '-',
    connection_id: '-',
    caused_by_action_id: '-',
    created_at: '-',
  },
  event_contents: {
    event_id: '-',
    tenant_id: '-',
    from_address: 'P',
    to_addresses: 'P',
    subject: 'I',
    body_text: 'I',
    attachments: 'I',
    retain_until: '-',
    created_at: '-',
  },
  event_entities: {
    tenant_id: '-',
    event_id: '-',
    entity_id: '-',
    role: '-',
    linked_by: '-',
    created_at: '-',
  },
  tasks: {
    id: '-',
    tenant_id: '-',
    title: 'I',
    notes: 'I',
    due_at: '-',
    status: '-',
    assignee_user_id: '-',
    created_by: '-',
    completed_at: '-',
    completed_by_user_id: '-',
    origin_card_id: '-',
    ...source,
    created_at: '-',
    updated_at: '-',
  },
  task_entities: {
    tenant_id: '-',
    task_id: '-',
    entity_id: '-',
    created_at: '-',
  },
  connections: {
    id: '-',
    tenant_id: '-',
    provider: '-',
    nango_integration_id: '-',
    nango_connection_id: '-',
    external_account_id: '-',
    account_label: 'P',
    status: '-',
    status_reason: '-',
    status_changed_at: '-',
    last_synced_at: '-',
    connected_by_user_id: '-',
    created_at: '-',
    updated_at: '-',
  },
  entity_external_refs: {
    id: '-',
    tenant_id: '-',
    entity_id: '-',
    connection_id: '-',
    provider: '-',
    object_type: '-',
    external_id: '-',
    created_at: '-',
  },
  cards: {
    id: '-',
    tenant_id: '-',
    kind: '-',
    status: '-',
    title: 'I',
    summary: 'I',
    // A suggested task has a title (free text); the rest is IDs and amounts.
    payload: 'I',
    priority: '-',
    dedupe_key: '-',
    connection_id: '-',
    task_id: '-',
    snoozed_until: '-',
    resolved_at: '-',
    resolved_by_user_id: '-',
    ai_model: '-',
    ai_trace_id: '-',
    created_at: '-',
    updated_at: '-',
  },
  card_events: {
    tenant_id: '-',
    card_id: '-',
    event_id: '-',
    created_at: '-',
  },
  card_entities: {
    tenant_id: '-',
    card_id: '-',
    entity_id: '-',
    created_at: '-',
  },
  actions: {
    id: '-',
    tenant_id: '-',
    card_id: '-',
    connection_id: '-',
    type: '-',
    status: '-',
    proposed_input: 'I',
    input: 'I',
    input_purged_at: '-',
    idempotency_key: '-',
    provider_object_id: '-',
    result: '-',
    approved_by_user_id: '-',
    approved_at: '-',
    executed_at: '-',
    attempts: '-',
    last_error_code: '-',
    ai_model: '-',
    ai_trace_id: '-',
    created_at: '-',
    updated_at: '-',
  },
  // No personal data by design: the metadata schemas allow no free text (#040).
  audit_log: {
    id: '-',
    tenant_id: '-',
    occurred_at: '-',
    actor_type: '-',
    actor_user_id: '-',
    action: '-',
    object_type: '-',
    object_id: '-',
    from_status: '-',
    to_status: '-',
    metadata: '-',
    request_id: '-',
    job_id: '-',
  },
};
