/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InloggenRouteImport } from './routes/inloggen'
import { Route as KoppelingenRouteImport } from './routes/koppelingen'
import { Route as RegistrerenRouteImport } from './routes/registreren'
import { Route as TestfoutRouteImport } from './routes/testfout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InloggenRoute = InloggenRouteImport.update({
  id: '/inloggen',
  path: '/inloggen',
  getParentRoute: () => rootRouteImport,
} as any)
const KoppelingenRoute = KoppelingenRouteImport.update({
  id: '/koppelingen',
  path: '/koppelingen',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrerenRoute = RegistrerenRouteImport.update({
  id: '/registreren',
  path: '/registreren',
  getParentRoute: () => rootRouteImport,
} as any)
const TestfoutRoute = TestfoutRouteImport.update({
  id: '/testfout',
  path: '/testfout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inloggen': typeof InloggenRoute
  '/koppelingen': typeof KoppelingenRoute
  '/registreren': typeof RegistrerenRoute
  '/testfout': typeof TestfoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inloggen': typeof InloggenRoute
  '/koppelingen': typeof KoppelingenRoute
  '/registreren': typeof RegistrerenRoute
  '/testfout': typeof TestfoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inloggen': typeof InloggenRoute
  '/koppelingen': typeof KoppelingenRoute
  '/registreren': typeof RegistrerenRoute
  '/testfout': typeof TestfoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inloggen' | '/koppelingen' | '/registreren' | '/testfout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inloggen' | '/koppelingen' | '/registreren' | '/testfout'
  id:
    | '__root__'
    | '/'
    | '/inloggen'
    | '/koppelingen'
    | '/registreren'
    | '/testfout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InloggenRoute: typeof InloggenRoute
  KoppelingenRoute: typeof KoppelingenRoute
  RegistrerenRoute: typeof RegistrerenRoute
  TestfoutRoute: typeof TestfoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inloggen': {
      id: '/inloggen'
      path: '/inloggen'
      fullPath: '/inloggen'
      preLoaderRoute: typeof InloggenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koppelingen': {
      id: '/koppelingen'
      path: '/koppelingen'
      fullPath: '/koppelingen'
      preLoaderRoute: typeof KoppelingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registreren': {
      id: '/registreren'
      path: '/registreren'
      fullPath: '/registreren'
      preLoaderRoute: typeof RegistrerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testfout': {
      id: '/testfout'
      path: '/testfout'
      fullPath: '/testfout'
      preLoaderRoute: typeof TestfoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InloggenRoute: InloggenRoute,
  KoppelingenRoute: KoppelingenRoute,
  RegistrerenRoute: RegistrerenRoute,
  TestfoutRoute: TestfoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
