-- Generated by drizzle-kit, then edited by hand (keep these edits when regenerating):
-- 1. The unique constraint on member(organization_id, user_id) is moved before
--    the foreign keys that reference it.
-- 2. `ON DELETE set null` became `ON DELETE SET NULL (column)` (PG15+), so only
--    the reference is cleared and tenant_id stays (docs/data-model.md §3.1).
CREATE TABLE "entities" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"type" text NOT NULL,
	"name" text NOT NULL,
	"attributes" jsonb NOT NULL,
	"archived_at" timestamp with time zone,
	"merged_into_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "entities_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "entities_type" CHECK ("entities"."type" in ('contact', 'company', 'project')),
	CONSTRAINT "entities_attributes_object" CHECK (jsonb_typeof("entities"."attributes") = 'object'),
	CONSTRAINT "entities_not_merged_into_self" CHECK ("entities"."merged_into_id" <> "entities"."id")
);
--> statement-breakpoint
ALTER TABLE "entities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "entity_identifiers" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"entity_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"value" text NOT NULL,
	"source_type" text NOT NULL,
	"source_event_id" uuid,
	"source_user_id" uuid,
	"ai_model" text,
	"ai_trace_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "entity_identifiers_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "entity_identifiers_tenant_kind_value_unique" UNIQUE("tenant_id","kind","value"),
	CONSTRAINT "entity_identifiers_kind" CHECK ("entity_identifiers"."kind" in ('email', 'phone', 'email_domain', 'kvk')),
	CONSTRAINT "entity_identifiers_source_type" CHECK ("entity_identifiers"."source_type" in ('event', 'document', 'user', 'action', 'system'))
);
--> statement-breakpoint
ALTER TABLE "entity_identifiers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "relations" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"from_entity_id" uuid NOT NULL,
	"to_entity_id" uuid NOT NULL,
	"type" text NOT NULL,
	"status" text NOT NULL,
	"valid_from" timestamp with time zone DEFAULT now() NOT NULL,
	"valid_to" timestamp with time zone,
	"confirmed_by_user_id" uuid,
	"confirmed_at" timestamp with time zone,
	"source_type" text NOT NULL,
	"source_event_id" uuid,
	"source_user_id" uuid,
	"ai_model" text,
	"ai_trace_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "relations_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "relations_type" CHECK ("relations"."type" in ('works_at', 'contact_for', 'client_of', 'part_of')),
	CONSTRAINT "relations_status" CHECK ("relations"."status" in ('proposed', 'confirmed', 'rejected')),
	CONSTRAINT "relations_source_type" CHECK ("relations"."source_type" in ('event', 'document', 'user', 'action', 'system')),
	CONSTRAINT "relations_distinct_entities" CHECK ("relations"."from_entity_id" <> "relations"."to_entity_id"),
	CONSTRAINT "relations_valid_period" CHECK ("relations"."valid_to" is null or "relations"."valid_to" > "relations"."valid_from"),
	CONSTRAINT "relations_confirmed_at" CHECK ("relations"."status" <> 'confirmed' or "relations"."confirmed_at" is not null)
);
--> statement-breakpoint
ALTER TABLE "relations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "event_contents" (
	"event_id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"from_address" text,
	"to_addresses" text[],
	"subject" text,
	"body_text" text,
	"attachments" jsonb,
	"retain_until" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "event_contents_attachments_array" CHECK ("event_contents"."attachments" is null or jsonb_typeof("event_contents"."attachments") = 'array')
);
--> statement-breakpoint
ALTER TABLE "event_contents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "event_entities" (
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"event_id" uuid NOT NULL,
	"entity_id" uuid NOT NULL,
	"role" text NOT NULL,
	"linked_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "event_entities_event_id_entity_id_role_pk" PRIMARY KEY("event_id","entity_id","role"),
	CONSTRAINT "event_entities_role" CHECK ("event_entities"."role" in ('sender', 'recipient', 'subject', 'mentioned')),
	CONSTRAINT "event_entities_linked_by" CHECK ("event_entities"."linked_by" in ('rule', 'ai', 'user'))
);
--> statement-breakpoint
ALTER TABLE "event_entities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "events" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"source" text NOT NULL,
	"external_id" text NOT NULL,
	"type" text NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"thread_key" text,
	"summary" text,
	"summarized_at" timestamp with time zone,
	"payload" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "events_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "events_tenant_source_external_id_unique" UNIQUE("tenant_id","source","external_id"),
	CONSTRAINT "events_source" CHECK ("events"."source" in ('gmail', 'outlook', 'moneybird', 'mollie', 'app')),
	CONSTRAINT "events_type" CHECK ("events"."type" in ('email.received', 'email.sent', 'quote.sent', 'quote.accepted', 'invoice.sent', 'payment.paid', 'payment.failed', 'action.executed', 'note.added')),
	CONSTRAINT "events_payload_object" CHECK (jsonb_typeof("events"."payload") = 'object'),
	CONSTRAINT "events_summarized" CHECK (("events"."summary" is null) = ("events"."summarized_at" is null))
);
--> statement-breakpoint
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "task_entities" (
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"task_id" uuid NOT NULL,
	"entity_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "task_entities_task_id_entity_id_pk" PRIMARY KEY("task_id","entity_id")
);
--> statement-breakpoint
ALTER TABLE "task_entities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"title" text NOT NULL,
	"notes" text,
	"due_at" timestamp with time zone,
	"status" text DEFAULT 'open' NOT NULL,
	"assignee_user_id" uuid,
	"created_by" text NOT NULL,
	"completed_at" timestamp with time zone,
	"completed_by_user_id" uuid,
	"source_type" text NOT NULL,
	"source_event_id" uuid,
	"source_user_id" uuid,
	"ai_model" text,
	"ai_trace_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tasks_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "tasks_status" CHECK ("tasks"."status" in ('open', 'done', 'cancelled')),
	CONSTRAINT "tasks_created_by" CHECK ("tasks"."created_by" in ('ai', 'user')),
	CONSTRAINT "tasks_source_type" CHECK ("tasks"."source_type" in ('event', 'document', 'user', 'action', 'system')),
	CONSTRAINT "tasks_completed" CHECK (("tasks"."status" = 'done') = ("tasks"."completed_at" is not null))
);
--> statement-breakpoint
ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tenant_settings" ADD COLUMN "content_retention_days" integer DEFAULT 90 NOT NULL;--> statement-breakpoint
-- Target of the composite member foreign keys below; must exist before them.
ALTER TABLE "member" ADD CONSTRAINT "member_organization_id_user_id_unique" UNIQUE("organization_id","user_id");--> statement-breakpoint
ALTER TABLE "entities" ADD CONSTRAINT "entities_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entities" ADD CONSTRAINT "entities_merged_into_fk" FOREIGN KEY ("tenant_id","merged_into_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE SET NULL ("merged_into_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_identifiers" ADD CONSTRAINT "entity_identifiers_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_identifiers" ADD CONSTRAINT "entity_identifiers_entity_fk" FOREIGN KEY ("tenant_id","entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_identifiers" ADD CONSTRAINT "entity_identifiers_source_event_fk" FOREIGN KEY ("tenant_id","source_event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE SET NULL ("source_event_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_identifiers" ADD CONSTRAINT "entity_identifiers_source_user_fk" FOREIGN KEY ("tenant_id","source_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("source_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "relations" ADD CONSTRAINT "relations_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "relations" ADD CONSTRAINT "relations_from_entity_fk" FOREIGN KEY ("tenant_id","from_entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "relations" ADD CONSTRAINT "relations_to_entity_fk" FOREIGN KEY ("tenant_id","to_entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "relations" ADD CONSTRAINT "relations_confirmed_by_fk" FOREIGN KEY ("tenant_id","confirmed_by_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("confirmed_by_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "relations" ADD CONSTRAINT "relations_source_event_fk" FOREIGN KEY ("tenant_id","source_event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE SET NULL ("source_event_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "relations" ADD CONSTRAINT "relations_source_user_fk" FOREIGN KEY ("tenant_id","source_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("source_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_contents" ADD CONSTRAINT "event_contents_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_contents" ADD CONSTRAINT "event_contents_event_fk" FOREIGN KEY ("tenant_id","event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_entities" ADD CONSTRAINT "event_entities_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_entities" ADD CONSTRAINT "event_entities_event_fk" FOREIGN KEY ("tenant_id","event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_entities" ADD CONSTRAINT "event_entities_entity_fk" FOREIGN KEY ("tenant_id","entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_entities" ADD CONSTRAINT "task_entities_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_entities" ADD CONSTRAINT "task_entities_task_fk" FOREIGN KEY ("tenant_id","task_id") REFERENCES "public"."tasks"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_entities" ADD CONSTRAINT "task_entities_entity_fk" FOREIGN KEY ("tenant_id","entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_assignee_fk" FOREIGN KEY ("tenant_id","assignee_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("assignee_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_completed_by_fk" FOREIGN KEY ("tenant_id","completed_by_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("completed_by_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_source_event_fk" FOREIGN KEY ("tenant_id","source_event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE SET NULL ("source_event_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_source_user_fk" FOREIGN KEY ("tenant_id","source_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("source_user_id") ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "entities_tenant_type_name_idx" ON "entities" USING btree ("tenant_id","type","name");--> statement-breakpoint
CREATE INDEX "entity_identifiers_tenant_entity_idx" ON "entity_identifiers" USING btree ("tenant_id","entity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "relations_current_unique" ON "relations" USING btree ("tenant_id","from_entity_id","to_entity_id","type") WHERE "relations"."valid_to" is null and "relations"."status" <> 'rejected';--> statement-breakpoint
CREATE INDEX "relations_tenant_to_entity_idx" ON "relations" USING btree ("tenant_id","to_entity_id");--> statement-breakpoint
CREATE INDEX "event_contents_tenant_retain_until_idx" ON "event_contents" USING btree ("tenant_id","retain_until");--> statement-breakpoint
CREATE INDEX "event_entities_tenant_entity_event_idx" ON "event_entities" USING btree ("tenant_id","entity_id","event_id");--> statement-breakpoint
CREATE INDEX "events_tenant_occurred_idx" ON "events" USING btree ("tenant_id","occurred_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "events_tenant_thread_idx" ON "events" USING btree ("tenant_id","thread_key");--> statement-breakpoint
CREATE INDEX "events_tenant_type_occurred_idx" ON "events" USING btree ("tenant_id","type","occurred_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "task_entities_tenant_entity_idx" ON "task_entities" USING btree ("tenant_id","entity_id");--> statement-breakpoint
CREATE INDEX "tasks_tenant_status_due_idx" ON "tasks" USING btree ("tenant_id","status","due_at");--> statement-breakpoint
CREATE INDEX "tasks_tenant_assignee_status_idx" ON "tasks" USING btree ("tenant_id","assignee_user_id","status");--> statement-breakpoint
ALTER TABLE "tenant_settings" ADD CONSTRAINT "tenant_settings_content_retention_days" CHECK ("tenant_settings"."content_retention_days" between 30 and 365);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "entities" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("entities"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("entities"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "entity_identifiers" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("entity_identifiers"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("entity_identifiers"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "relations" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("relations"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("relations"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "event_contents" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("event_contents"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("event_contents"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "event_entities" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("event_entities"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("event_entities"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "events" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("events"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("events"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "task_entities" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("task_entities"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("task_entities"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "tasks" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("tasks"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tasks"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);