-- Generated by drizzle-kit, then edited by hand (keep these edits when regenerating):
-- `ON DELETE set null` became `ON DELETE SET NULL (column)` (PG15+), so only
-- the reference is cleared and tenant_id stays (docs/data-model.md §3.1).
CREATE TABLE "actions" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"card_id" uuid NOT NULL,
	"connection_id" uuid NOT NULL,
	"type" text NOT NULL,
	"status" text DEFAULT 'concept' NOT NULL,
	"proposed_input" jsonb,
	"input" jsonb,
	"input_purged_at" timestamp with time zone,
	"idempotency_key" text NOT NULL,
	"provider_object_id" text,
	"result" jsonb,
	"approved_by_user_id" uuid,
	"approved_at" timestamp with time zone,
	"executed_at" timestamp with time zone,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"last_error_code" text,
	"ai_model" text,
	"ai_trace_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "actions_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "actions_tenant_idempotency_key_unique" UNIQUE("tenant_id","idempotency_key"),
	CONSTRAINT "actions_type" CHECK ("actions"."type" in ('email.reply', 'moneybird.quote', 'moneybird.invoice_reminder', 'mollie.payment_link')),
	CONSTRAINT "actions_status" CHECK ("actions"."status" in ('concept', 'approved', 'executed', 'failed', 'rejected')),
	CONSTRAINT "actions_executed_has_provider_object" CHECK ("actions"."status" <> 'executed' or "actions"."provider_object_id" is not null),
	CONSTRAINT "actions_approved" CHECK ("actions"."status" in ('concept', 'rejected') or "actions"."approved_at" is not null),
	CONSTRAINT "actions_inputs_present" CHECK (("actions"."input_purged_at" is null) = ("actions"."proposed_input" is not null and "actions"."input" is not null)),
	CONSTRAINT "actions_inputs_object" CHECK (("actions"."proposed_input" is null or jsonb_typeof("actions"."proposed_input") = 'object') and ("actions"."input" is null or jsonb_typeof("actions"."input") = 'object')),
	CONSTRAINT "actions_result_object" CHECK ("actions"."result" is null or jsonb_typeof("actions"."result") = 'object'),
	CONSTRAINT "actions_attempts" CHECK ("actions"."attempts" >= 0)
);
--> statement-breakpoint
ALTER TABLE "actions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"actor_type" text NOT NULL,
	"actor_user_id" uuid,
	"action" text NOT NULL,
	"object_type" text NOT NULL,
	"object_id" uuid,
	"from_status" text,
	"to_status" text,
	"metadata" jsonb NOT NULL,
	"request_id" text,
	"job_id" text,
	CONSTRAINT "audit_log_actor_type" CHECK ("audit_log"."actor_type" in ('user', 'agent', 'system')),
	CONSTRAINT "audit_log_actor_user" CHECK (("audit_log"."actor_type" = 'user') = ("audit_log"."actor_user_id" is not null)),
	CONSTRAINT "audit_log_action" CHECK ("audit_log"."action" in ('connection.created', 'connection.reactivated', 'connection.revoked', 'connection.expired', 'connection.purged', 'card.created', 'card.reopened', 'card.snoozed', 'card.done', 'card.dismissed', 'card.expired', 'action.proposed', 'action.approved', 'action.rejected', 'action.executed', 'action.failed', 'action.reopened')),
	CONSTRAINT "audit_log_object_type" CHECK ("audit_log"."object_type" in ('connections', 'cards', 'actions')),
	CONSTRAINT "audit_log_metadata_object" CHECK (jsonb_typeof("audit_log"."metadata") = 'object')
);
--> statement-breakpoint
ALTER TABLE "audit_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "card_entities" (
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"card_id" uuid NOT NULL,
	"entity_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "card_entities_card_id_entity_id_pk" PRIMARY KEY("card_id","entity_id")
);
--> statement-breakpoint
ALTER TABLE "card_entities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "card_events" (
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"card_id" uuid NOT NULL,
	"event_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "card_events_card_id_event_id_pk" PRIMARY KEY("card_id","event_id")
);
--> statement-breakpoint
ALTER TABLE "card_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "cards" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"kind" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"title" text NOT NULL,
	"summary" text,
	"payload" jsonb NOT NULL,
	"priority" smallint DEFAULT 1 NOT NULL,
	"dedupe_key" text,
	"connection_id" uuid,
	"task_id" uuid,
	"snoozed_until" timestamp with time zone,
	"resolved_at" timestamp with time zone,
	"resolved_by_user_id" uuid,
	"ai_model" text,
	"ai_trace_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cards_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "cards_kind" CHECK ("cards"."kind" in ('email_reply', 'quote_request', 'payment_overdue', 'connection_problem', 'knowledge_review', 'task_due', 'insight')),
	CONSTRAINT "cards_status" CHECK ("cards"."status" in ('open', 'snoozed', 'done', 'dismissed', 'expired')),
	CONSTRAINT "cards_payload_object" CHECK (jsonb_typeof("cards"."payload") = 'object'),
	CONSTRAINT "cards_priority" CHECK ("cards"."priority" between 0 and 3),
	CONSTRAINT "cards_resolved" CHECK (("cards"."status" in ('done', 'dismissed', 'expired')) = ("cards"."resolved_at" is not null)),
	CONSTRAINT "cards_snoozed" CHECK (("cards"."status" = 'snoozed') = ("cards"."snoozed_until" is not null)),
	CONSTRAINT "cards_connection_problem" CHECK (("cards"."kind" = 'connection_problem') = ("cards"."connection_id" is not null)),
	CONSTRAINT "cards_task_due" CHECK (("cards"."kind" = 'task_due') = ("cards"."task_id" is not null))
);
--> statement-breakpoint
ALTER TABLE "cards" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "connections" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"provider" text NOT NULL,
	"nango_integration_id" text NOT NULL,
	"nango_connection_id" text NOT NULL,
	"external_account_id" text,
	"account_label" text,
	"status" text DEFAULT 'active' NOT NULL,
	"status_reason" text,
	"status_changed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_synced_at" timestamp with time zone,
	"connected_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "connections_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "connections_nango_connection_id_unique" UNIQUE("nango_connection_id"),
	CONSTRAINT "connections_provider" CHECK ("connections"."provider" in ('gmail', 'outlook', 'moneybird', 'mollie')),
	CONSTRAINT "connections_status" CHECK ("connections"."status" in ('active', 'revoked', 'expired', 'purged')),
	CONSTRAINT "connections_status_reason" CHECK ("connections"."status_reason" is null or "connections"."status_reason" in ('invalid_grant', 'provider_revoked', 'user_disconnected', 'reauthorized', 'data_purged')),
	CONSTRAINT "connections_purged_label" CHECK ("connections"."status" <> 'purged' or "connections"."account_label" is null)
);
--> statement-breakpoint
ALTER TABLE "connections" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "entity_external_refs" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"entity_id" uuid NOT NULL,
	"connection_id" uuid NOT NULL,
	"provider" text NOT NULL,
	"object_type" text NOT NULL,
	"external_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "entity_external_refs_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "entity_external_refs_external_unique" UNIQUE("tenant_id","connection_id","object_type","external_id"),
	CONSTRAINT "entity_external_refs_provider" CHECK ("entity_external_refs"."provider" in ('gmail', 'outlook', 'moneybird', 'mollie'))
);
--> statement-breakpoint
ALTER TABLE "entity_external_refs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "entity_identifiers" ADD COLUMN "source_action_id" uuid;--> statement-breakpoint
ALTER TABLE "relations" ADD COLUMN "source_action_id" uuid;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "connection_id" uuid;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "caused_by_action_id" uuid;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "origin_card_id" uuid;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "source_action_id" uuid;--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_card_fk" FOREIGN KEY ("tenant_id","card_id") REFERENCES "public"."cards"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_connection_fk" FOREIGN KEY ("tenant_id","connection_id") REFERENCES "public"."connections"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_approved_by_fk" FOREIGN KEY ("tenant_id","approved_by_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("approved_by_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card_entities" ADD CONSTRAINT "card_entities_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card_entities" ADD CONSTRAINT "card_entities_card_fk" FOREIGN KEY ("tenant_id","card_id") REFERENCES "public"."cards"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card_entities" ADD CONSTRAINT "card_entities_entity_fk" FOREIGN KEY ("tenant_id","entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card_events" ADD CONSTRAINT "card_events_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card_events" ADD CONSTRAINT "card_events_card_fk" FOREIGN KEY ("tenant_id","card_id") REFERENCES "public"."cards"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "card_events" ADD CONSTRAINT "card_events_event_fk" FOREIGN KEY ("tenant_id","event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cards" ADD CONSTRAINT "cards_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cards" ADD CONSTRAINT "cards_connection_fk" FOREIGN KEY ("tenant_id","connection_id") REFERENCES "public"."connections"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cards" ADD CONSTRAINT "cards_task_fk" FOREIGN KEY ("tenant_id","task_id") REFERENCES "public"."tasks"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cards" ADD CONSTRAINT "cards_resolved_by_fk" FOREIGN KEY ("tenant_id","resolved_by_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("resolved_by_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connections" ADD CONSTRAINT "connections_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connections" ADD CONSTRAINT "connections_connected_by_fk" FOREIGN KEY ("tenant_id","connected_by_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("connected_by_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_external_refs" ADD CONSTRAINT "entity_external_refs_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_external_refs" ADD CONSTRAINT "entity_external_refs_entity_fk" FOREIGN KEY ("tenant_id","entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_external_refs" ADD CONSTRAINT "entity_external_refs_connection_fk" FOREIGN KEY ("tenant_id","connection_id") REFERENCES "public"."connections"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "actions_tenant_card_idx" ON "actions" USING btree ("tenant_id","card_id");--> statement-breakpoint
CREATE INDEX "actions_tenant_status_idx" ON "actions" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX "audit_log_tenant_occurred_idx" ON "audit_log" USING btree ("tenant_id","occurred_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "audit_log_tenant_object_idx" ON "audit_log" USING btree ("tenant_id","object_type","object_id");--> statement-breakpoint
CREATE INDEX "card_entities_tenant_entity_idx" ON "card_entities" USING btree ("tenant_id","entity_id");--> statement-breakpoint
CREATE INDEX "card_events_tenant_event_idx" ON "card_events" USING btree ("tenant_id","event_id");--> statement-breakpoint
CREATE UNIQUE INDEX "cards_open_dedupe_unique" ON "cards" USING btree ("tenant_id","dedupe_key") WHERE "cards"."status" in ('open', 'snoozed');--> statement-breakpoint
CREATE INDEX "cards_feed_idx" ON "cards" USING btree ("tenant_id","status","priority" DESC NULLS LAST,"created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "connections_active_account_unique" ON "connections" USING btree ("tenant_id","provider","external_account_id") WHERE "connections"."status" = 'active';--> statement-breakpoint
CREATE INDEX "connections_tenant_status_idx" ON "connections" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX "entity_external_refs_tenant_entity_idx" ON "entity_external_refs" USING btree ("tenant_id","entity_id");--> statement-breakpoint
ALTER TABLE "entity_identifiers" ADD CONSTRAINT "entity_identifiers_source_action_fk" FOREIGN KEY ("tenant_id","source_action_id") REFERENCES "public"."actions"("tenant_id","id") ON DELETE SET NULL ("source_action_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "relations" ADD CONSTRAINT "relations_source_action_fk" FOREIGN KEY ("tenant_id","source_action_id") REFERENCES "public"."actions"("tenant_id","id") ON DELETE SET NULL ("source_action_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_connection_fk" FOREIGN KEY ("tenant_id","connection_id") REFERENCES "public"."connections"("tenant_id","id") ON DELETE SET NULL ("connection_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_caused_by_action_fk" FOREIGN KEY ("tenant_id","caused_by_action_id") REFERENCES "public"."actions"("tenant_id","id") ON DELETE SET NULL ("caused_by_action_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_origin_card_fk" FOREIGN KEY ("tenant_id","origin_card_id") REFERENCES "public"."cards"("tenant_id","id") ON DELETE SET NULL ("origin_card_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_source_action_fk" FOREIGN KEY ("tenant_id","source_action_id") REFERENCES "public"."actions"("tenant_id","id") ON DELETE SET NULL ("source_action_id") ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "actions" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("actions"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("actions"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation_select" ON "audit_log" AS PERMISSIVE FOR SELECT TO "app_runtime" USING ("audit_log"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation_insert" ON "audit_log" AS PERMISSIVE FOR INSERT TO "app_runtime" WITH CHECK ("audit_log"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "card_entities" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("card_entities"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("card_entities"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "card_events" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("card_events"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("card_events"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "cards" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("cards"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("cards"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "connections" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("connections"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("connections"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "entity_external_refs" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("entity_external_refs"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("entity_external_refs"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);