-- Generated by drizzle-kit, then edited by hand (keep these edits when regenerating):
-- `ON DELETE set null` became `ON DELETE SET NULL (column)` (PG15+), so only
-- the reference is cleared and tenant_id stays (docs/data-model.md §3.1).
CREATE TABLE "chunk_embeddings" (
	"chunk_id" uuid NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"model" text NOT NULL,
	"model_version" text NOT NULL,
	"dimensions" smallint NOT NULL,
	"embedding" vector NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chunk_embeddings_chunk_id_model_pk" PRIMARY KEY("chunk_id","model"),
	CONSTRAINT "chunk_embeddings_model" CHECK (("chunk_embeddings"."model", "chunk_embeddings"."model_version", "chunk_embeddings"."dimensions") in (('cohere-embed-v5', 'embed-v5.0-pro', 1024), ('cohere-embed-v5', 'embed-v5.0-fast', 1024))),
	CONSTRAINT "chunk_embeddings_dimensions" CHECK (vector_dims("chunk_embeddings"."embedding") = "chunk_embeddings"."dimensions")
);
--> statement-breakpoint
ALTER TABLE "chunk_embeddings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "company_profile" (
	"tenant_id" uuid PRIMARY KEY DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"trade_name" text NOT NULL,
	"kvk_number" text,
	"vat_number" text,
	"sector" text NOT NULL,
	"services_description" text,
	"service_area" text,
	"tone_of_voice" text,
	"email_signature" text,
	"opening_hours" jsonb,
	"details" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "company_profile_sector" CHECK ("company_profile"."sector" in ('installation', 'construction', 'gardening', 'cleaning', 'events', 'photography', 'business_services', 'other')),
	CONSTRAINT "company_profile_opening_hours_object" CHECK ("company_profile"."opening_hours" is null or jsonb_typeof("company_profile"."opening_hours") = 'object'),
	CONSTRAINT "company_profile_details_object" CHECK (jsonb_typeof("company_profile"."details") = 'object')
);
--> statement-breakpoint
ALTER TABLE "company_profile" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "document_chunks" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"document_id" uuid NOT NULL,
	"ordinal" integer NOT NULL,
	"heading_path" text,
	"content" text NOT NULL,
	"token_count" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "document_chunks_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "document_chunks_document_ordinal_unique" UNIQUE("document_id","ordinal"),
	CONSTRAINT "document_chunks_ordinal" CHECK ("document_chunks"."ordinal" >= 0),
	CONSTRAINT "document_chunks_token_count" CHECK ("document_chunks"."token_count" >= 0)
);
--> statement-breakpoint
ALTER TABLE "document_chunks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "document_entities" (
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"document_id" uuid NOT NULL,
	"entity_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "document_entities_document_id_entity_id_pk" PRIMARY KEY("document_id","entity_id")
);
--> statement-breakpoint
ALTER TABLE "document_entities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "documents" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"title" text NOT NULL,
	"origin" text NOT NULL,
	"connection_id" uuid,
	"external_id" text,
	"storage_key" text,
	"mime_type" text NOT NULL,
	"byte_size" bigint NOT NULL,
	"sha256" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"uploaded_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "documents_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "documents_tenant_sha256_unique" UNIQUE("tenant_id","sha256"),
	CONSTRAINT "documents_origin" CHECK ("documents"."origin" in ('upload', 'connection')),
	CONSTRAINT "documents_status" CHECK ("documents"."status" in ('pending', 'processing', 'ready', 'failed')),
	CONSTRAINT "documents_connection" CHECK (("documents"."origin" = 'connection') = ("documents"."connection_id" is not null and "documents"."external_id" is not null)),
	CONSTRAINT "documents_byte_size" CHECK ("documents"."byte_size" >= 0),
	CONSTRAINT "documents_sha256" CHECK ("documents"."sha256" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
ALTER TABLE "documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "fact_embeddings" (
	"fact_id" uuid NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"model" text NOT NULL,
	"model_version" text NOT NULL,
	"dimensions" smallint NOT NULL,
	"embedding" vector NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "fact_embeddings_fact_id_model_pk" PRIMARY KEY("fact_id","model"),
	CONSTRAINT "fact_embeddings_model" CHECK (("fact_embeddings"."model", "fact_embeddings"."model_version", "fact_embeddings"."dimensions") in (('cohere-embed-v5', 'embed-v5.0-pro', 1024), ('cohere-embed-v5', 'embed-v5.0-fast', 1024))),
	CONSTRAINT "fact_embeddings_dimensions" CHECK (vector_dims("fact_embeddings"."embedding") = "fact_embeddings"."dimensions")
);
--> statement-breakpoint
ALTER TABLE "fact_embeddings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "facts" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"entity_id" uuid NOT NULL,
	"statement" text NOT NULL,
	"attribute" text,
	"structured" jsonb,
	"status" text DEFAULT 'proposed' NOT NULL,
	"confidence" real,
	"valid_from" timestamp with time zone DEFAULT now() NOT NULL,
	"valid_to" timestamp with time zone,
	"superseded_by_id" uuid,
	"confirmed_by_user_id" uuid,
	"confirmed_at" timestamp with time zone,
	"last_confirmed_at" timestamp with time zone,
	"source_type" text NOT NULL,
	"source_event_id" uuid,
	"source_chunk_id" uuid,
	"source_user_id" uuid,
	"source_action_id" uuid,
	"ai_model" text,
	"ai_trace_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "facts_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "facts_status" CHECK ("facts"."status" in ('proposed', 'confirmed', 'rejected')),
	CONSTRAINT "facts_source_type" CHECK ("facts"."source_type" in ('event', 'document', 'user', 'action', 'system')),
	CONSTRAINT "facts_confidence" CHECK ("facts"."confidence" between 0 and 1),
	CONSTRAINT "facts_valid_period" CHECK ("facts"."valid_to" is null or "facts"."valid_to" > "facts"."valid_from"),
	CONSTRAINT "facts_confirmed_at" CHECK ("facts"."status" <> 'confirmed' or "facts"."confirmed_at" is not null),
	CONSTRAINT "facts_superseded_ended" CHECK ("facts"."superseded_by_id" is null or "facts"."valid_to" is not null),
	CONSTRAINT "facts_not_superseded_by_self" CHECK ("facts"."superseded_by_id" <> "facts"."id"),
	CONSTRAINT "facts_structured" CHECK ("facts"."structured" is null or (jsonb_typeof("facts"."structured") = 'object' and "facts"."structured"->>'attribute' = "facts"."attribute"))
);
--> statement-breakpoint
ALTER TABLE "facts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "insights" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"kind" text NOT NULL,
	"entity_id" uuid,
	"payload" jsonb NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "insights_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "insights_tenant_kind_entity_unique" UNIQUE NULLS NOT DISTINCT("tenant_id","kind","entity_id"),
	CONSTRAINT "insights_kind" CHECK ("insights"."kind" in ('open_quotes', 'payment_behaviour')),
	CONSTRAINT "insights_entity" CHECK (("insights"."kind" in ('payment_behaviour')) = ("insights"."entity_id" is not null)),
	CONSTRAINT "insights_payload_object" CHECK (jsonb_typeof("insights"."payload") = 'object'),
	CONSTRAINT "insights_expiry" CHECK ("insights"."expires_at" > "insights"."computed_at")
);
--> statement-breakpoint
ALTER TABLE "insights" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "playbook_embeddings" (
	"playbook_id" uuid NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"model" text NOT NULL,
	"model_version" text NOT NULL,
	"dimensions" smallint NOT NULL,
	"embedding" vector NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "playbook_embeddings_playbook_id_model_pk" PRIMARY KEY("playbook_id","model"),
	CONSTRAINT "playbook_embeddings_model" CHECK (("playbook_embeddings"."model", "playbook_embeddings"."model_version", "playbook_embeddings"."dimensions") in (('cohere-embed-v5', 'embed-v5.0-pro', 1024), ('cohere-embed-v5', 'embed-v5.0-fast', 1024))),
	CONSTRAINT "playbook_embeddings_dimensions" CHECK (vector_dims("playbook_embeddings"."embedding") = "playbook_embeddings"."dimensions")
);
--> statement-breakpoint
ALTER TABLE "playbook_embeddings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "playbook_examples" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"playbook_id" uuid NOT NULL,
	"source_event_id" uuid,
	"source_action_id" uuid,
	"input_excerpt" text NOT NULL,
	"output_text" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "playbook_examples_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "playbook_examples_has_source" CHECK ("playbook_examples"."source_event_id" is not null or "playbook_examples"."source_action_id" is not null)
);
--> statement-breakpoint
ALTER TABLE "playbook_examples" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "playbooks" (
	"id" uuid PRIMARY KEY DEFAULT public.gen_uuid_v7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"title" text NOT NULL,
	"trigger_description" text NOT NULL,
	"instruction" text NOT NULL,
	"template" text,
	"scope" text NOT NULL,
	"scope_user_id" uuid,
	"scope_entity_id" uuid,
	"status" text DEFAULT 'proposed' NOT NULL,
	"version" smallint DEFAULT 1 NOT NULL,
	"supersedes_id" uuid,
	"confirmed_by_user_id" uuid,
	"confirmed_at" timestamp with time zone,
	"source_type" text NOT NULL,
	"source_event_id" uuid,
	"source_chunk_id" uuid,
	"source_user_id" uuid,
	"source_action_id" uuid,
	"ai_model" text,
	"ai_trace_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "playbooks_tenant_id_id_unique" UNIQUE("tenant_id","id"),
	CONSTRAINT "playbooks_scope" CHECK ("playbooks"."scope" in ('company', 'user', 'customer')),
	CONSTRAINT "playbooks_status" CHECK ("playbooks"."status" in ('proposed', 'confirmed', 'rejected', 'retired')),
	CONSTRAINT "playbooks_source_type" CHECK ("playbooks"."source_type" in ('event', 'document', 'user', 'action', 'system')),
	CONSTRAINT "playbooks_scope_user" CHECK (("playbooks"."scope" = 'user') = ("playbooks"."scope_user_id" is not null)),
	CONSTRAINT "playbooks_scope_customer" CHECK (("playbooks"."scope" = 'customer') = ("playbooks"."scope_entity_id" is not null)),
	CONSTRAINT "playbooks_confirmed_at" CHECK ("playbooks"."status" not in ('confirmed', 'retired') or "playbooks"."confirmed_at" is not null),
	CONSTRAINT "playbooks_version" CHECK ("playbooks"."version" >= 1),
	CONSTRAINT "playbooks_not_superseding_self" CHECK ("playbooks"."supersedes_id" <> "playbooks"."id")
);
--> statement-breakpoint
ALTER TABLE "playbooks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "audit_log" DROP CONSTRAINT "audit_log_action";--> statement-breakpoint
ALTER TABLE "audit_log" DROP CONSTRAINT "audit_log_object_type";--> statement-breakpoint
ALTER TABLE "actions" ADD COLUMN "playbook_id" uuid;--> statement-breakpoint
ALTER TABLE "entity_identifiers" ADD COLUMN "source_chunk_id" uuid;--> statement-breakpoint
ALTER TABLE "relations" ADD COLUMN "source_chunk_id" uuid;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "source_chunk_id" uuid;--> statement-breakpoint
ALTER TABLE "chunk_embeddings" ADD CONSTRAINT "chunk_embeddings_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chunk_embeddings" ADD CONSTRAINT "chunk_embeddings_chunk_fk" FOREIGN KEY ("tenant_id","chunk_id") REFERENCES "public"."document_chunks"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "company_profile" ADD CONSTRAINT "company_profile_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_chunks" ADD CONSTRAINT "document_chunks_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_chunks" ADD CONSTRAINT "document_chunks_document_fk" FOREIGN KEY ("tenant_id","document_id") REFERENCES "public"."documents"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_entities" ADD CONSTRAINT "document_entities_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_entities" ADD CONSTRAINT "document_entities_document_fk" FOREIGN KEY ("tenant_id","document_id") REFERENCES "public"."documents"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_entities" ADD CONSTRAINT "document_entities_entity_fk" FOREIGN KEY ("tenant_id","entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_connection_fk" FOREIGN KEY ("tenant_id","connection_id") REFERENCES "public"."connections"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_uploaded_by_fk" FOREIGN KEY ("tenant_id","uploaded_by_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("uploaded_by_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fact_embeddings" ADD CONSTRAINT "fact_embeddings_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fact_embeddings" ADD CONSTRAINT "fact_embeddings_fact_fk" FOREIGN KEY ("tenant_id","fact_id") REFERENCES "public"."facts"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facts" ADD CONSTRAINT "facts_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facts" ADD CONSTRAINT "facts_entity_fk" FOREIGN KEY ("tenant_id","entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facts" ADD CONSTRAINT "facts_superseded_by_fk" FOREIGN KEY ("tenant_id","superseded_by_id") REFERENCES "public"."facts"("tenant_id","id") ON DELETE SET NULL ("superseded_by_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facts" ADD CONSTRAINT "facts_confirmed_by_fk" FOREIGN KEY ("tenant_id","confirmed_by_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("confirmed_by_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facts" ADD CONSTRAINT "facts_source_event_fk" FOREIGN KEY ("tenant_id","source_event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE SET NULL ("source_event_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facts" ADD CONSTRAINT "facts_source_chunk_fk" FOREIGN KEY ("tenant_id","source_chunk_id") REFERENCES "public"."document_chunks"("tenant_id","id") ON DELETE SET NULL ("source_chunk_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facts" ADD CONSTRAINT "facts_source_user_fk" FOREIGN KEY ("tenant_id","source_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("source_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facts" ADD CONSTRAINT "facts_source_action_fk" FOREIGN KEY ("tenant_id","source_action_id") REFERENCES "public"."actions"("tenant_id","id") ON DELETE SET NULL ("source_action_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "insights" ADD CONSTRAINT "insights_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "insights" ADD CONSTRAINT "insights_entity_fk" FOREIGN KEY ("tenant_id","entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbook_embeddings" ADD CONSTRAINT "playbook_embeddings_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbook_embeddings" ADD CONSTRAINT "playbook_embeddings_playbook_fk" FOREIGN KEY ("tenant_id","playbook_id") REFERENCES "public"."playbooks"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbook_examples" ADD CONSTRAINT "playbook_examples_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbook_examples" ADD CONSTRAINT "playbook_examples_playbook_fk" FOREIGN KEY ("tenant_id","playbook_id") REFERENCES "public"."playbooks"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbook_examples" ADD CONSTRAINT "playbook_examples_source_event_fk" FOREIGN KEY ("tenant_id","source_event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbook_examples" ADD CONSTRAINT "playbook_examples_source_action_fk" FOREIGN KEY ("tenant_id","source_action_id") REFERENCES "public"."actions"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_tenant_id_organization_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_scope_user_fk" FOREIGN KEY ("tenant_id","scope_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_scope_entity_fk" FOREIGN KEY ("tenant_id","scope_entity_id") REFERENCES "public"."entities"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_supersedes_fk" FOREIGN KEY ("tenant_id","supersedes_id") REFERENCES "public"."playbooks"("tenant_id","id") ON DELETE SET NULL ("supersedes_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_confirmed_by_fk" FOREIGN KEY ("tenant_id","confirmed_by_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("confirmed_by_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_source_event_fk" FOREIGN KEY ("tenant_id","source_event_id") REFERENCES "public"."events"("tenant_id","id") ON DELETE SET NULL ("source_event_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_source_chunk_fk" FOREIGN KEY ("tenant_id","source_chunk_id") REFERENCES "public"."document_chunks"("tenant_id","id") ON DELETE SET NULL ("source_chunk_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_source_user_fk" FOREIGN KEY ("tenant_id","source_user_id") REFERENCES "public"."member"("organization_id","user_id") ON DELETE SET NULL ("source_user_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_source_action_fk" FOREIGN KEY ("tenant_id","source_action_id") REFERENCES "public"."actions"("tenant_id","id") ON DELETE SET NULL ("source_action_id") ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "chunk_embeddings_tenant_model_idx" ON "chunk_embeddings" USING btree ("tenant_id","model");--> statement-breakpoint
CREATE INDEX "document_entities_tenant_entity_idx" ON "document_entities" USING btree ("tenant_id","entity_id");--> statement-breakpoint
CREATE INDEX "documents_tenant_status_idx" ON "documents" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX "fact_embeddings_tenant_model_idx" ON "fact_embeddings" USING btree ("tenant_id","model");--> statement-breakpoint
CREATE UNIQUE INDEX "facts_current_unique" ON "facts" USING btree ("tenant_id","entity_id","attribute") WHERE "facts"."status" = 'confirmed' and "facts"."valid_to" is null and "facts"."attribute" is not null;--> statement-breakpoint
CREATE INDEX "facts_tenant_entity_status_idx" ON "facts" USING btree ("tenant_id","entity_id","status") WHERE "facts"."valid_to" is null;--> statement-breakpoint
CREATE INDEX "facts_tenant_status_created_idx" ON "facts" USING btree ("tenant_id","status","created_at");--> statement-breakpoint
CREATE INDEX "insights_tenant_entity_idx" ON "insights" USING btree ("tenant_id","entity_id");--> statement-breakpoint
CREATE INDEX "playbook_embeddings_tenant_model_idx" ON "playbook_embeddings" USING btree ("tenant_id","model");--> statement-breakpoint
CREATE INDEX "playbook_examples_tenant_playbook_idx" ON "playbook_examples" USING btree ("tenant_id","playbook_id");--> statement-breakpoint
CREATE INDEX "playbooks_tenant_status_scope_idx" ON "playbooks" USING btree ("tenant_id","status","scope");--> statement-breakpoint
CREATE INDEX "playbooks_tenant_scope_entity_idx" ON "playbooks" USING btree ("tenant_id","scope_entity_id");--> statement-breakpoint
CREATE INDEX "playbooks_tenant_supersedes_idx" ON "playbooks" USING btree ("tenant_id","supersedes_id");--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_playbook_fk" FOREIGN KEY ("tenant_id","playbook_id") REFERENCES "public"."playbooks"("tenant_id","id") ON DELETE SET NULL ("playbook_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_identifiers" ADD CONSTRAINT "entity_identifiers_source_chunk_fk" FOREIGN KEY ("tenant_id","source_chunk_id") REFERENCES "public"."document_chunks"("tenant_id","id") ON DELETE SET NULL ("source_chunk_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "relations" ADD CONSTRAINT "relations_source_chunk_fk" FOREIGN KEY ("tenant_id","source_chunk_id") REFERENCES "public"."document_chunks"("tenant_id","id") ON DELETE SET NULL ("source_chunk_id") ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_source_chunk_fk" FOREIGN KEY ("tenant_id","source_chunk_id") REFERENCES "public"."document_chunks"("tenant_id","id") ON DELETE SET NULL ("source_chunk_id") ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "actions_tenant_playbook_idx" ON "actions" USING btree ("tenant_id","playbook_id");--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_action" CHECK ("audit_log"."action" in ('connection.created', 'connection.reactivated', 'connection.revoked', 'connection.expired', 'connection.purged', 'card.created', 'card.reopened', 'card.snoozed', 'card.done', 'card.dismissed', 'card.expired', 'action.proposed', 'action.approved', 'action.rejected', 'action.executed', 'action.failed', 'action.reopened', 'fact.confirmed', 'fact.rejected', 'fact.superseded', 'playbook.confirmed', 'playbook.rejected', 'playbook.retired'));--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_object_type" CHECK ("audit_log"."object_type" in ('connections', 'cards', 'actions', 'facts', 'playbooks'));--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "chunk_embeddings" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("chunk_embeddings"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("chunk_embeddings"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "company_profile" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("company_profile"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("company_profile"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "document_chunks" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("document_chunks"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("document_chunks"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "document_entities" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("document_entities"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("document_entities"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "documents" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("documents"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("documents"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "fact_embeddings" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("fact_embeddings"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("fact_embeddings"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "facts" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("facts"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("facts"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "insights" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("insights"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("insights"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "playbook_embeddings" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("playbook_embeddings"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("playbook_embeddings"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "playbook_examples" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("playbook_examples"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("playbook_examples"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "playbooks" AS PERMISSIVE FOR ALL TO "app_runtime" USING ("playbooks"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("playbooks"."tenant_id" = nullif(current_setting('app.tenant_id', true), '')::uuid);